use gc200397613;

CREATE TABLE reviews

(reviewId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

username VARCHAR(100) NOT NULL,

rating INT NOT NULL,

comments VARCHAR(5000),

reviewDate DATETIME DEFAULT CURRENT_TIMESTAMP, 

movie VARCHAR(100) NOT NULL);